apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    project: roboshop
    tier: db
spec:
  selector:
    matchLabels:
      app: redis
      project: roboshop
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "redis"
  replicas: {{ .Values.stateful.replicas }} # by default is 1
  template:
    metadata:
        labels:
          app: redis
          project: roboshop
          tier: db # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: redis
        image: "iamroyalreddy/redis:{{ .Values.stateful.imageVersion }}"
        volumeMounts:
        - name: redis
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
